import type { Metadata } from 'next';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import '@/styles/globals.css';

import { StoreInitializer } from '@/components/store-initializer';

export const metadata: Metadata = {
  title: 'AI Chat Assistant',
  description: 'Generated by AI Chat Assistant',
  icons: {
    icon: '/icons/favicon.ico',
  },
};

/**
 * Root layout component that wraps all pages with global styles and font variables.
 * Renders the application's children within an HTML structure set to English, applying Geist Sans and Geist Mono fonts and antialiasing to the body.
 * @param children - The page content to be rendered inside the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={`${GeistSans.className} antialiased`}>
        <StoreInitializer />
        {children}
      </body>
    </html>
  );
}
