import type { Metadata } from 'next';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import '@/styles/globals.css';

import { StoreInitializer } from '@/components/store-initializer';

export const metadata: Metadata = {
  title: 'AI Chat Assistant',
  description: 'Generated by AI Chat Assistant',
  icons: {
    icon: '/icons/favicon.ico',
  },
};

/**
 * Root layout for all application pages, applying global styles, fonts, and initializing the store.
 *
 * Wraps every page in a consistent HTML structure with Geist Sans and Geist Mono fonts, antialiasing, and global state initialization.
 *
 * @param children - The page content to render within the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={`${GeistSans.className} antialiased`}>
        <StoreInitializer />
        {children}
      </body>
    </html>
  );
}
